### ISSUE TITLE
Team Project Discussion

### ISSUE THREAD

**Issue by zmatteson** [CS3398-Espresso-Noir/-CS3398-Espresso-F2017#1]
Hey team,  I'm creating this story for Assignment 4.

[A4+-+Team+Project+Discussion.pdf](https://github.com/CS3398-Espresso-Noir/-CS3398-Espresso-F2017/files/1301185/A4.-.Team.Project.Discussion.pdf)

**Comment by m-r525** [comment]
We decided to create a weather application for Android that alerts the user of inclement weather.
