### ISSUE TITLE
User Sign-In Research

### ISSUE THREAD

**Issue by m-r525** [CS3398-Espresso-Noir/-CS3398-Espresso-F2017#39]
Research how to implement user sign-in with email, facebook, etc.

**Comment by zmatteson** [comment]
Read tutorials on 
https://firebase.google.com/docs/auth/android/start/
https://firebase.google.com/docs/auth/android/manage-users
https://firebase.google.com/docs/auth/android/password-auth
https://firebase.google.com/docs/auth/android/google-signin
